### ISSUE TITLE
issue with PHP 5.3

### ISSUE THREAD

**Issue by edgar-mtz-e** [Akshay-Hegde/grocery_crud_multiuploader#1]
Please refer to http://www.grocerycrud.com/forums/topic/2850-grocery-crud-multiuploader-library/?p=12533

There I explain and upload edited library to support PHP 5.3 However when uploading a file I get null as a result (Firebug says so).

Best regards

**Comment by Akshay-Hegde** [comment]
The null issue is fixed, please look at function upload_file
