### ISSUE TITLE
Problem with Grocery_CRUD_Model

### ISSUE THREAD

**Issue by flick36** [Akshay-Hegde/grocery_crud_multiuploader#2]
Hi, first of allnice plugin! but i have some problems implementing it

A PHP Error was encountered

Severity: Runtime Notice

Message: Declaration of Grocery_CRUD_Multiuploader::upload_file() should be compatible with grocery_CRUD_Model_Driver::upload_file($state_info)

Filename: libraries/Grocery_CRUD_Multiuploader.php

Line Number: 963

and:

A PHP Error was encountered

Severity: Runtime Notice

Message: Declaration of Grocery_CRUD_Multiuploader::delete_file() should be compatible with grocery_CRUD_Model_Driver::delete_file($state_info)

Filename: libraries/Grocery_CRUD_Multiuploader.php

Line Number: 0

**Comment by Akshay-Hegde** [comment]
Hi flick36, fixed the issue kindly download updated Grocery_CRUD_Multiuploader.php file.
