### ISSUE TITLE
Breaks functionality of built-in single file uploader of Grocery CRUD

### ISSUE THREAD

**Issue by Daninet** [Akshay-Hegde/grocery_crud_multiuploader#3]
I've found a bug: you cannot mix multiupload fields with single file upload fields.
It displays correctly, but when you want to upload something at the simple upload field, it throws this error message from javascript: "An error has occurred on uploading."

Ajax response from controller/function/upload_file/image (there are 2 objects):

```
{"error":"You did not select a file to upload. Allowed file types are gif|jpeg|jpg|png|tiff|doc|docx|txt|odt|xls|xlsx|pdf|ppt|pptx|pps|ppsx|mp3|m4a|ogg|wav|mp4|m4v|mov|wmv|flv|avi|mpg|ogv|3gp|3g2","success":"false"}{"success":true,"files":null}
```

**Comment by mravac** [comment]
Solution:
Rename function upload_file to multiupload_file in line 673 and 199

Then, both single upload and multi upload work.

**Comment by Akshay-Hegde** [comment]
Thanks mravac, let me update
