### ISSUE TITLE
Object of class Grocery_CRUD_Multiuploader could not be converted to string

### ISSUE THREAD

**Issue by abdallahmaali** [Akshay-Hegde/grocery_crud_multiuploader#6]
A PHP Error was encountered

Severity: 4096

Message: Object of class Grocery_CRUD_Multiuploader could not be converted to string

Filename: libraries/Grocery_CRUD_Multiuploader.php

Line Number: 862

i have this problem its accrued after submitted  the form in success page 

Backtrace:

File: C:\xampp\htdocs\pharmacare\application\libraries\Grocery_CRUD_Multiuploader.php
Line: 862
Function: _error_handler

File: C:\xampp\htdocs\pharmacare\application\libraries\Grocery_CRUD_Multiuploader.php
Line: 118
Function: call_user_func

File: C:\xampp\htdocs\pharmacare\application\libraries\Grocery_CRUD.php
Line: 1553
Function: change_list

File: C:\xampp\htdocs\pharmacare\application\libraries\Grocery_CRUD.php
Line: 4482
Function: showList

File: C:\xampp\htdocs\pharmacare\application\controllers\multiuploader.php
Line: 119
Function: render

File: C:\xampp\htdocs\pharmacare\index.php
Line: 292
Function: require_once

**Comment by Akshay-Hegde** [comment]
Please mention, the the version of php and gc you are using

**Comment by abdallahmaali** [comment]
thanks i fixed the problem but i want to use another function  in grocery crude 
like  unset_cloumns   when i call this method i have this problem 

/**/
 Call to undefined method Multiuploader::unset_columns()
/***/

could you help me how i can use the grocery crude functions

**Comment by abdallahmaali** [comment]
i found the solution   i added 
  parent::__construct(); 

in Grocery_CRUD_Multiuploader class  in construct function 
many thanks for this great plugin you made my life easy  :)

**Comment by Akshay-Hegde** [comment]
Welcome.
